version: '3.8'

services:
  podcast_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - assets:/app/assets
    environment:
      - FLASK_ENV=development

volumes:
  assets:
